### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by BoJlod9I** [nesQuick/atom-wordcount#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: linux 3.2.0-75-generic
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package, v0.13.1

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /usr/share/atom/resources/app/node_modules/emissary/lib/subscriber.js:25

TypeError: Cannot read property 'on' of undefined
  at WordcountView.module.exports.Subscriber.subscribeWith (/usr/share/atom/resources/app/node_modules/emissary/lib/subscriber.js:25:23)
  at WordcountView.module.exports.Subscriber.subscribe (/usr/share/atom/resources/app/node_modules/emissary/lib/subscriber.js:63:21)
  at WordcountView.module.exports.WordcountView.initialize (/home/diamonik/.atom/packages/wordcount/lib/wordcount-view.coffee:17:6)
  at WordcountView.View (/usr/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
  at new WordcountView (/home/diamonik/.atom/packages/wordcount/lib/wordcount-view.coffee:5:3)
  at /home/diamonik/.atom/packages/wordcount/lib/wordcount.coffee:14:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "material-design-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide",
      "tabs",
      "powerline",
      "vim-mode",
      "atom-charcode",
      "atom-status-text",
      "buildbox-status",
      "codeship-status",
      "cursor-count",
      "editor-stats",
      "error-status",
      "git-tab-status",
      "status-stats",
      "status-bar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.3
filesize, v0.1.1
function-name-in-status-bar, v0.2.6
language-html5-subtlegradient, v0.1.0
material-design-syntax, v1.5.0
seti-ui, v0.6.3
time-status, v1.0.1
wordcount, v0.13.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by claman** [comment]
How do you reproduce this?
