### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by markoa** [nesQuick/atom-wordcount#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package, v2.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/marko/.atom/packages/wordcount/lib/main.coffee:20

TypeError: undefined is not a function
  at /Users/marko/.atom/packages/wordcount/lib/main.coffee:20:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:211:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:318:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:329:19)
  at DisplayBuffer.module.exports.DisplayBuffer.setWidth (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:452:14)
  at TextEditor.module.exports.TextEditor.setWidth (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2958:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.setContentFrameWidth (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:923:20)
  at TextEditorComponent.module.exports.TextEditorComponent.measureHeightAndWidth (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:832:31)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:249:12)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:790:16)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:91:22)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:328:21)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:534:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
  4x -1:02.5 core:backspace (atom-text-editor.editor.is-focused)
     -1:00.0 core:save (atom-text-editor.editor.is-focused)
     -0:58.0 core:close (atom-text-editor.editor.is-focused)
     -0:52.8 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -0:44.1 core:confirm (atom-text-editor.editor.mini)
     -0:38.9 fuzzy-finder:toggle-file-finder (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:37.1 core:confirm (atom-text-editor.editor.mini)
     -0:26.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:21.4 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:21.4 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:19.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:07.9 core:close (button.btn.icon.icon-playback-play)
     -0:03.0 fuzzy-finder:toggle-file-finder (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  3x -0:01.7 core:backspace (atom-text-editor.editor.mini)
     -0:00.5 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "wordcount"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
tag, v0.2.3

# Dev
No dev packages
```

**Comment by afischer** [comment]
+1

**Comment by trcook** [comment]
I also received this error after updating. It did not throw again after restarting atom, however. Possibly just a one-off problem in the update process?

**Comment by nesQuick** [comment]
Is this still valid? Never heard about this issue again :tada: Please let me know if it still exist in the current version!
