### ISSUE TITLE
Failed to load the wordcount package

### ISSUE THREAD

**Issue by anjerodesu** [nesQuick/atom-wordcount#58]
[Enter steps to reproduce below:]

1. Open .md file
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package, v2.6.0

### Stack Trace

Failed to load the wordcount package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/angelo/.atom/packages/wordcount/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at Object.<anonymous> (/Users/angelo/.atom/packages/wordcount/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/angelo/.atom/packages/wordcount/lib/wordcount-view.coffee:1:10)
    at Object.<anonymous> (/Users/angelo/.atom/packages/wordcount/lib/wordcount-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/angelo/.atom/packages/wordcount/lib/main.coffee:1:17)
    at Object.<anonymous> (/Users/angelo/.atom/packages/wordcount/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
file-icons, v1.6.15
highlight-selected, v0.11.2
language-haskell, v1.5.2
language-latex, v0.6.1
language-swift, v0.4.0
latex, v0.29.0
linter-swiftc, v2.0.0
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by nesQuick** [comment]
`space-pen` is a package which should ship with the atom editor since 1.0 could you try to reinstall the plugin again?

**Comment by Avonaeon** [comment]
I have version 1.12.7 installed and this still happened. Tried re-installing the wordcount package twice with the same error.

**Comment by nesQuick** [comment]
@Avonaeon please update to the latest version: `2.10.2`

**Comment by Avonaeon** [comment]
I meant I have Atom version 1.12.7. I'm already using the 2.10.2 version of wordcount.

**Comment by nesQuick** [comment]
Could you please use the atom report feature? So I have all versions and
the actual trace :+1:

**Comment by Avonaeon** [comment]
Atom doesn't seem to allow to report an existing issue, I just see "View Issue". Here's the stack trace though:

**Comment by nesQuick** [comment]
@Avonaeon thank you very much. I don't see how I could debug this, sorry :(
